### ISSUE TITLE
Error: Connection Failed

### ISSUE THREAD

**Issue by aister** [usini/usini_discord_webhook#1]
I've made a simple code sending a message to discord via webhook, but it only successfully sent the message the first time only, and then getting an Error: Connection Failed with a http code of -1 for the rest of the time until I reset the board. And then the same thing happens again.

I've been looking around but I haven't found any solutions for this yet. WIFI connection is fine, connection to discord is fine, since I can send the message the first time, and the webhook isn't rate limited.

**Comment by remisarrailh** [comment]
Thanks for the report, i'll check it out, tomorrow.

**Comment by remisarrailh** [comment]
I tried on a esp32 : No issue
I tried on a esp8266 : Connection failed after first sent

Seems to be an issue on the esp8266 part.
I'll tried to fix it.

**Comment by remisarrailh** [comment]
Ok I find the issue, version 1.0.1 should be available on the library manager soon.
If you don't want to wait you can find it here : https://github.com/usini/usini_discord_webhook/releases/tag/1.0.1

You can find how to install a library using a zip file here : https://www.ardu-badge.com/Discord_WebHook/zip
