### ISSUE TITLE
Discord_WebHook compile error

### ISSUE THREAD

**Issue by soontai** [usini/usini_discord_webhook#3]
I USE ESP32S COMPILE EXAMPLE INO (helloword.ino) ERROR
Discord_WebHook : VER 1.0.1
Arduino IDE : 2.3.3
IDE board : NodeMCU-32S

c:\Users\username\Documents\Arduino\libraries\Discord_WebHook\src\Discord_WebHook.cpp: In member function 'bool Discord_Webhook::send(String)':
c:\Users\username\Documents\Arduino\libraries\Discord_WebHook\src\Discord_WebHook.cpp:75:3: error: 'WiFiClientSecure' was not declared in this scope; did you mean 'WiFiClient'?
   75 |   WiFiClientSecure *client = new WiFiClientSecure; // Create a WiFiClientSecure
      |   ^~~~~~~~~~~~~~~~
      |   WiFiClient
c:\Users\username\Documents\Arduino\libraries\Discord_WebHook\src\Discord_WebHook.cpp:75:21: error: 'client' was not declared in this scope; did you mean 'Client'?
   75 |   WiFiClientSecure *client = new WiFiClientSecure; // Create a WiFiClientSecure
      |                     ^~~~~~
      |                     Client
c:\Users\username\Documents\Arduino\libraries\Discord_WebHook\src\Discord_WebHook.cpp:75:34: error: 'WiFiClientSecure' does not name a type; did you mean 'WiFiClient'?
   75 |   WiFiClientSecure *client = new WiFiClientSecure; // Create a WiFiClientSecure
      |                                  ^~~~~~~~~~~~~~~~
      |                                  WiFiClient
c:\Users\username\Documents\Arduino\libraries\Discord_WebHook\src\Discord_WebHook.cpp:137:10: error: type '<type error>' argument given to 'delete', expected pointer
  137 |   delete client;
      |          ^~~~~~
Multiple libraries were found for "WiFi.h"
  Used: C:\Users\username\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.5\libraries\WiFi
  Not used: C:\Users\username\Documents\Arduino\libraries\WiFiEspAT
exit status 1

Compilation error: exit status 1

**Comment by remisarrailh** [comment]
Fixed the issue,
https://github.com/usini/usini_discord_webhook/releases/tag/1.1.0
Unfortunately it takes a bit of time for Arduino to update it

--> You can download the zip directly 
--> Or use DisCard library instead which is basically a copy of mine with the fix
https://github.com/pxsty0/DisCard/
